### PR TITLE
Sidechain system and networking diagram

### PR DESCRIPTION
**Pull request by murerfel**
Closes https://github.com/integritee-network/worker/issues/625

### CODE REVIEW

**Review by brenzi — CHANGES_REQUESTED** [review]
please upload svg, not png. Otherwise we'll have to look for the sources if we need to make changes. mdbook supports svg

otherwise: very helpful diagram I think. Still: an instance view could be interesting too, which shows three validateers, each with their own local node and an outside node for indirect invocation by the cli client

**Comment by murerfel** [comment]
I replaced the `.png` with an `.svg` file now and added a new diagram, for a multi-validateer setup with local nodes. Is that more or less what you meant?

**Review by brenzi — APPROVED** [review]
yes, it is. thx!

**Comment by murerfel** [comment]
Alright, then may I ask you to merge it, since I cannot? ☺️

**Pull request merged**
